### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by borjaruiz** [dibakarece/AndroidFileExplorer#2]
Hi, I would like to use this in my app.

I would like to open your "MainActivity" from my Activity and start browsing files, but I call your MainActivity and it crashes. 

Thanks in advance.

**Comment by dibakarece** [comment]
Ok i will give you an exmple

**Comment by dibakarece** [comment]
If you want to choose some file from your Directory like PDF/Exel/DOC.....etc define the type in the code.....in my exmple i only choose PDF extension so i define here PDF.

Exm  :https://www.dropbox.com/s/7thcqk60yb26djr/FileExpDemo.zip?dl=0
