### ISSUE TITLE
Can I specifier the file browser types

### ISSUE THREAD

**Issue by pixelbendr** [dibakarece/AndroidFileExplorer#3]
I want to restrict browsing to just images and videos files. Is this Possible? also can you provide a simple usage example?

**Comment by dibakarece** [comment]
You can use my another project that is OwnGalleryView which can help to load image and videos.Go through the classes "PhoneMediaControl" and "PhoneMediaVideoController" for load Image and videos

**Comment by pixelbendr** [comment]
Thanks you so much for this.

**Comment by pixelbendr** [comment]
The project not Android Studio so am not able to use it. Can you help convert it?

**Comment by dibakarece** [comment]
You can use my classes in your Android Studio project to get the actual output.I have not more time  in my hand,If possible then definitely, I will send a demo to help your integration.

**Comment by dibakarece** [comment]
@pixelbendr I have updated the source code in studio version,please see my latest source code.

**Comment by pixelbendr** [comment]
@dibaakar thank you.
